const data = {
  products: [
    {
      name: "Bandă elastică",
      slug: "banda-elastica",
      category: "Antrenament",
      image: "/images/bandaElastica.jpg",
      price: 33,
      countInStock: 10,
      brand: "GymBeam",
      numberOfReviews: 5,
      rating: 4,
      description: "Bandă Elastică de înaltă calitate.",
    },
    {
      name: "Bandaj pentru Încheieturi",
      slug: "bandaj-incheieturi",
      category: "Antrenament",
      image: "/images/bandajIncheieturi.jpg",
      price: 30,
      countInStock: 20,
      brand: "GymBeam",
      numberOfReviews: 7,
      rating: 4.5,
      description: "Bandaj pentru Încheieturi de inaltă calitate.",
    },
    {
      name: "Shaker Portocaliu",
      slug: "shaker-portocaliu",
      category: "Alimentație și nutriție",
      image: "/images/shakerPortocaliu.jpg",
      price: 17,
      countInStock: 35,
      brand: "GymBeam",
      numberOfReviews: 12,
      rating: 5,
      description: "Shaker de calitate superioară.",
    },
  ],
};
export default data;
